# This is the default JWT configuration and need to be updated when used to issue JWT tokens. It is a component that used to
# issue JWT token. Normally, it should be used by light-oauth2 only but can be used to issue tokens distributely.
---
# Signature private key that used to sign JWT tokens.
key:
  kid: '100'
  filename: "primary.jks"
  keyName: selfsigned
  password: password
issuer: urn:com:networknt:oauth2:v1
audience: urn:com.networknt
expiredInMinutes: 10
version: '1.0'
