// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"authorize/index":{"path":"authorize","id":"authorize/index"},"success/index":{"path":"success","id":"success/index"},"login/index":{"path":"login","id":"login/index"}} as const;
  return {
    routes,
    routeComponents: {
'authorize/index': React.lazy(() => import(/* webpackChunkName: "src__pages__authorize__index" */'../../../src/pages/authorize/index.tsx')),
'success/index': React.lazy(() => import(/* webpackChunkName: "src__pages__success__index" */'../../../src/pages/success/index.tsx')),
'login/index': React.lazy(() => import(/* webpackChunkName: "src__pages__login__index" */'../../../src/pages/login/index.tsx')),
},
  };
}
