# Cors Http Handler Configuration. This is to support connection
# from light-portal single page application which might served
# from another domain/host. You may need to update allowedOrigins.
---
description: Cors Http Handler
enabled: true
allowedOrigins:
  - http://localhost:8000
  - https://localhost:8000
allowedMethods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
allowedHeaders:
  - Content-Type
  - Authorization
  - X-Requested-With
  - X-Request-ID
  - X-XSRF-TOKEN
allowCredentials: true # 允许携带凭证
